export const originalData = [
  { id: 1, name: "Emily", meaning: "Industrious" },
  { id: 2, name: "James", meaning: "Supplanter" },
  { id: 3, name: "Sophia", meaning: "Wisdom" },
  { id: 4, name: "William", meaning: "Strong-willed warrior" },
  { id: 5, name: "Olivia", meaning: "Olive tree" },
  { id: 6, name: "Alexander", meaning: "Defender of the people" },
  { id: 7, name: "Emma", meaning: "Whole" },
  { id: 8, name: "Michael", meaning: "Who is like God?" },
  { id: 9, name: "Ava", meaning: "Bird" },
  { id: 10, name: "Ethan", meaning: "Strong, firm" },
  { id: 11, name: "Isabella", meaning: "God is my oath" },
  { id: 12, name: "Daniel", meaning: "God is my judge" },
  { id: 13, name: "Mia", meaning: "Mine" },
  { id: 14, name: "Matthew", meaning: "Gift of God" },
  { id: 15, name: "Charlotte", meaning: "Free man" },
  { id: 16, name: "Jacob", meaning: "Supplanter" },
  { id: 17, name: "Madison", meaning: "Son of Maud" },
  { id: 18, name: "William", meaning: "Strong-willed warrior" },
  { id: 19, name: "Abigail", meaning: "My father is joyful" },
  { id: 20, name: "Elijah", meaning: "My God is Yahweh" },
  { id: 21, name: "Harper", meaning: "Harp player" },
  { id: 22, name: "Benjamin", meaning: "Son of the right hand" },
  { id: 23, name: "Sofia", meaning: "Wisdom" },
  { id: 24, name: "Lucas", meaning: "Light-giving" },
  { id: 25, name: "Mila", meaning: "Gracious" },
  { id: 26, name: "Noah", meaning: "Rest, comfort" },
  { id: 27, name: "Avery", meaning: "Ruler of the elves" },
  { id: 28, name: "Grace", meaning: "God's favor" },
  { id: 29, name: "Liam", meaning: "Strong-willed warrior" },
  { id: 30, name: "Chloe", meaning: "Blooming" },
  { id: 31, name: "Evelyn", meaning: "Desired, wished for" },
  { id: 32, name: "Logan", meaning: "Small hollow" },
  { id: 33, name: "Lily", meaning: "Pure, innocent" },
  { id: 34, name: "Jack", meaning: "God is gracious" },
  { id: 35, name: "Scarlett", meaning: "Red" },
  { id: 36, name: "Owen", meaning: "Well-born, young warrior" },
  { id: 37, name: "Aria", meaning: "Air, song, melody" },
  { id: 38, name: "Carter", meaning: "Transporter of goods by cart" },
  { id: 39, name: "Nora", meaning: "Honor" },
  { id: 40, name: "Gabriel", meaning: "God is my strength" },
  { id: 41, name: "Savannah", meaning: "Treeless plain" },
  { id: 42, name: "Grayson", meaning: "Son of a steward" },
  { id: 43, name: "Stella", meaning: "Star" },
  { id: 44, name: "Jackson", meaning: "Son of Jack" },
  { id: 45, name: "Aurora", meaning: "Dawn" },
  { id: 46, name: "Liam", meaning: "Strong-willed warrior" },
  { id: 47, name: "Zoe", meaning: "Life" },
  { id: 48, name: "Mason", meaning: "Worker in stone" },
  { id: 49, name: "Elena", meaning: "Bright, shining light" },
  { id: 50, name: "Connor", meaning: "Lover of hounds" },
  { id: 51, name: "Aiden", meaning: "Fiery one" },
  { id: 52, name: "Madeline", meaning: "Woman from Magdala" },
  { id: 53, name: "Ezra", meaning: "Helper" },
  { id: 54, name: "Hannah", meaning: "Grace" },
  { id: 55, name: "Nathan", meaning: "Gift of God" },
  { id: 56, name: "Leah", meaning: "Weary" },
  { id: 57, name: "Ryan", meaning: "Little king" },
  { id: 58, name: "Audrey", meaning: "Noble strength" },
  { id: 59, name: "Samuel", meaning: "God has heard" },
  { id: 60, name: "Adeline", meaning: "Noble" },
  { id: 61, name: "Evan", meaning: "God is gracious" },
  { id: 62, name: "Grace", meaning: "God's favor" },
  { id: 63, name: "Colton", meaning: "From the dark town" },
  { id: 64, name: "Elizabeth", meaning: "God is my oath" },
  { id: 65, name: "Nicholas", meaning: "Victory of the people" },
  { id: 66, name: "Luna", meaning: "Moon" },
  { id: 67, name: "Eliana", meaning: "My God has answered" },
  { id: 68, name: "David", meaning: "Beloved" },
  { id: 69, name: "Julia", meaning: "Youthful" },
  { id: 70, name: "Gabriel", meaning: "God is my strength" },
  { id: 71, name: "Isaac", meaning: "He will laugh" },
  { id: 72, name: "Hazel", meaning: "The hazel tree" },
  { id: 73, name: "Andrew", meaning: "Manly, brave" },
  { id: 74, name: "Violet", meaning: "Purple/blue flower" },
  { id: 75, name: "Caleb", meaning: "Faithful, devoted" },
  { id: 76, name: "Aria", meaning: "Melody, air" },
  { id: 77, name: "Lucy", meaning: "Light" },
  { id: 78, name: "Luke", meaning: "Light-giving" },
  { id: 79, name: "Julian", meaning: "Youthful, downy-bearded" },
  { id: 80, name: "Clara", meaning: "Bright, clear" },
  { id: 81, name: "Oscar", meaning: "Divine spear" },
  { id: 82, name: "Isla", meaning: "Island" },
  { id: 83, name: "Max", meaning: "Greatest" },
  { id: 84, name: "Natalie", meaning: "Born on Christmas day" },
  { id: 85, name: "Austin", meaning: "Great" },
  { id: 86, name: "Nova", meaning: "New" },
  { id: 87, name: "Felix", meaning: "Happy, fortunate" },
  { id: 88, name: "Ruby", meaning: "Deep red precious stone" },
  { id: 89, name: "Sebastian", meaning: "Venerable, revered" },
  { id: 90, name: "Aurora", meaning: "Dawn" },
  { id: 91, name: "Eleanor", meaning: "Bright, shining light" },
  { id: 92, name: "Mason", meaning: "Worker in stone" },
  { id: 93, name: "Autumn", meaning: "Fall season" },
  { id: 94, name: "Xavier", meaning: "Bright, splendid" },
  { id: 95, name: "Aurora", meaning: "Dawn" },
  { id: 96, name: "Samantha", meaning: "Listener" },
  { id: 97, name: "Axel", meaning: "Father of peace" },
  { id: 98, name: "Ivy", meaning: "Climbing vine plant" },
  { id: 99, name: "Theodore", meaning: "Gift of God" },
  { id: 100, name: "Emilia", meaning: "To strive or excel or rival" },
];

export let searchData = [...originalData]; // Create a copy of original data for searching
